### ISSUE TITLE
go2shy.Tracer dont implement opentracing.Tracer?

### ISSUE THREAD

**Issue by LvBay** [SkyAPM/go2sky#23]
Is the future planning to define a new set of trace protocols or to comply with opentracing?

**Comment by wu-sheng** [comment]
OpenTracing is changing, combining with OpenCensus, to OpenTelemetry. It is chaos and disorder in such API definitions. If you want to take part in, we are willing to discuss that, set up an OT implementation bridge.

**Comment by LvBay** [comment]
@wu-sheng  Thank you for your answer. I didn't know the change in opentracing that you said before.

Since we used Jaeger before our project, we are now trying to access Skywalking. If go2sky also implements the opentracing interface, then we will be easy to migrate.

As far as you say opentracing is chaos, I will read the relevant information. Or can you elaborate on it? I will thank you very much.

**Comment by wu-sheng** [comment]
I am open to elaborate, also the primary author @hanahmily is open to join.  The key difference between the designs is we are requiring 
1. Provide span kind(entry/local/exist) when creating span
1. If exist span created, the peer(target ip:port) is required at first place, or at least before inject op.

Others should be very similar because I am aware of OT and be part of OT specification  council for a long time, even it didn't go well from 2 years ago.

**Comment by hanahmily** [comment]
`OpenTracing` is on our roadmap, but recently I haven't time to push the plan. If you want to contribute to that key feature, I really appreciate it.

**Comment by shuxnhs** [comment]
Has anyone achieved this bridge, thanks!
